/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screen;

import enums.Quadrante;
import entidades.Ponto;

/**
 *
 * @author Felipe
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldX = new javax.swing.JTextField();
        jTextFieldY = new javax.swing.JTextField();
        jButtonAvaliar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxEixoX = new javax.swing.JCheckBox();
        jCheckBoxEixoY = new javax.swing.JCheckBox();
        jCheckBoxQuadrante01 = new javax.swing.JCheckBox();
        jCheckBoxQuadrante02 = new javax.swing.JCheckBox();
        jCheckBoxQuadrante03 = new javax.swing.JCheckBox();
        jCheckBoxQuadrante04 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X:");

        jLabel2.setText("Eixo Y:");

        jTextFieldX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXActionPerformed(evt);
            }
        });

        jTextFieldY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYActionPerformed(evt);
            }
        });

        jButtonAvaliar.setText("Avaliar");
        jButtonAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvaliarActionPerformed(evt);
            }
        });

        jLabel3.setText("Posição");

        jCheckBoxEixoX.setText("Incide sobre eixo X");
        jCheckBoxEixoX.setEnabled(false);
        jCheckBoxEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEixoXActionPerformed(evt);
            }
        });

        jCheckBoxEixoY.setText("Incide sobre eixo Y");
        jCheckBoxEixoY.setEnabled(false);

        jCheckBoxQuadrante01.setText("No primeiro quadrante");
        jCheckBoxQuadrante01.setEnabled(false);

        jCheckBoxQuadrante02.setText("No segundo quadrante");
        jCheckBoxQuadrante02.setEnabled(false);

        jCheckBoxQuadrante03.setText("No terceiro quadrante");
        jCheckBoxQuadrante03.setEnabled(false);

        jCheckBoxQuadrante04.setText("No quarto quadrante");
        jCheckBoxQuadrante04.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldX, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jTextFieldY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAvaliar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxEixoX)
                            .addComponent(jCheckBoxEixoY)
                            .addComponent(jCheckBoxQuadrante01)
                            .addComponent(jCheckBoxQuadrante02)
                            .addComponent(jCheckBoxQuadrante03)
                            .addComponent(jCheckBoxQuadrante04))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButtonAvaliar)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxEixoX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEixoY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxQuadrante01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxQuadrante02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxQuadrante03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxQuadrante04)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldYActionPerformed

    private void jTextFieldXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldXActionPerformed

    private void jCheckBoxEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEixoXActionPerformed

    private void jButtonAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvaliarActionPerformed
        String xText = jTextFieldX.getText();
        String yText = jTextFieldY.getText();
        
        if (xText.isBlank() || xText.isEmpty() || yText.isBlank() || yText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha ambos os campos X e Y.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!xText.matches("[0-9.]+") || !yText.matches("[0-9.]+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, os campos devem ser preenchidos por números", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int x = Integer.parseInt(xText);
        int y = Integer.parseInt(yText);
        
        
        Ponto ponto = new Ponto(x, y);
        
        jCheckBoxEixoX.setSelected(false);
        jCheckBoxEixoY.setSelected(false);
        jCheckBoxQuadrante01.setSelected(false);
        jCheckBoxQuadrante02.setSelected(false);
        jCheckBoxQuadrante03.setSelected(false);
        jCheckBoxQuadrante04.setSelected(false);

        
        if (ponto.estaIncidindoSobreX()) {
            jCheckBoxEixoX.setSelected(true);
        }
        
        if (ponto.estaIncidindoSobreY()) {
            jCheckBoxEixoY.setSelected(true);
        }
        
        if (ponto.indentificarQuadrante() == Quadrante.PRIMEIRO) {
            jCheckBoxQuadrante01.setSelected(true);
        }
        
        if (ponto.indentificarQuadrante() == Quadrante.SEGUNDO) {
            jCheckBoxQuadrante02.setSelected(true);
        }
        
        if (ponto.indentificarQuadrante() == Quadrante.TERCEIRO) {
            jCheckBoxQuadrante03.setSelected(true);
        }
        
        if (ponto.indentificarQuadrante() == Quadrante.QUARTO) {
            jCheckBoxQuadrante04.setSelected(true);
        }
    }//GEN-LAST:event_jButtonAvaliarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvaliar;
    private javax.swing.JCheckBox jCheckBoxEixoX;
    private javax.swing.JCheckBox jCheckBoxEixoY;
    private javax.swing.JCheckBox jCheckBoxQuadrante01;
    private javax.swing.JCheckBox jCheckBoxQuadrante02;
    private javax.swing.JCheckBox jCheckBoxQuadrante03;
    private javax.swing.JCheckBox jCheckBoxQuadrante04;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldY;
    // End of variables declaration//GEN-END:variables
}
